# yaml-language-server: $schema= https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  nerdFontsVersion: "3"
  language: "en"
  switchTabsWithPanelJumpKeys: true
  statusPanelView: allBranchesLog
  # border: 'hidden'
  showNumstatInFilesView: true
  showRandomTip: false
  showBottomLine: false
  filterMode: fuzzy
  showCommandLog: false
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 4
  branchColorPatterns:
    '^bugfix': 'red'
    '^feature': 'green'
    '^develop': 'cyan'
    '^release': 'magenta'
    '^(master|main)': 'yellow'
  spinner:
    rate: 83
    frames: [
      '', '', '', '', '', ''
    ]
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - black
      - bold
    selectedLineBgColor:
      - reverse
  customIcons:
    extensions:
      ".http":
        icon: '󱂛'
        color: '#5050FF'
git:
  localBranchSortOrder: recency
  mainBranches: [main, master, develop]
  paging:
    useExternalDiffGitConfig: true
    colorArg: always
notARepository: 'quit'
os:
  open: 'nvim {{filename}}'
  editPreset: 'nvim'
